defmodule ScoreTrackerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :score_tracker

  alias ScoreTrackerWeb.SessionOptions

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: {SessionOptions, :get, []}]],
    longpoll: [connect_info: [session: {SessionOptions, :get, []}]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :score_tracker,
    gzip: not code_reloading?,
    only: ScoreTrackerWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, SessionOptions.get()
  plug ScoreTrackerWeb.Router
end
