name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    env:
      MIX_ENV: test
      # Values from .env.example
      SCORE_TRACKER_SECRET_KEY_BASE: "hQxqLAdGePykqr4yIGvW0xIWkVX8EPC2Clt3CrSrH0mDgyy7yRrymz1dEA3Vw8P+"
      SCORE_TRACKER_LIVE_VIEW_SIGNING_SALT: "Eym7G0NcGR4X+Fg1k13J8FnW2ya9eJ0Q"
      SCORE_TRACKER_SESSION_ENCRYPTION_SALT: "Cn3tctEZr8jv4OiPGCWiCWedfjmWbL6S"
      SCORE_TRACKER_SESSION_SIGNING_SALT: "dl+FpTlZFshOqAJGRFr7YSG3GkX2fPM9"
      SCORE_TRACKER_CACHE_POOL_SIZE: 5
      SCORE_TRACKER_CACHE_URL: valkey://localhost:6379

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          version-file: .tool-versions
          version-type: strict
      - name: Install dependencies
        run: mix deps.get
      - name: Remove compiled application files
        run: mix clean
      - name: Compile and lint dependencies
        run: mix compile --warnings-as-errors
      - name: Check code formatting
        run: mix format --check-formatted
      - name: Run credo
        run: mix credo --strict
      - name: Run sobelow
        run: mix sobelow --config
      - name: Run tests
        run: mix test
